name: build-test

on: 
  push:
    branches: 
      - main
      - develop
    paths:
      - '**.cs'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.cs'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./RabiRiichiTests/RabiRiichiTests.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore ./RabiRiichiTests/RabiRiichiTests.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" ./RabiRiichiTests/RabiRiichiTests.csproj
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate Test Report
        uses: phoenix-actions/test-reporting@v3
        id: test-report
        if: success() || failure()
        with:
          name: RabiRiichi Tests
          path: RabiRiichiTests/TestResults/*.trx
          reporter: dotnet-trx
