name: build-test

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./RabiRiichiTests/RabiRiichiTests.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore ./RabiRiichiTests/RabiRiichiTests.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" ./RabiRiichiTests/RabiRiichiTests.csproj
      - name: Copy Coverage Report To Root
        run: |
          shopt -s globstar
          cp ./RabiRiichiTests/TestResults/**/coverage.xml ./cov.xml
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov.xml